### ISSUE TITLE
Optionally Hide Groups

### ISSUE THREAD

**Issue by konistehrad** [chrivers/bifrost#16]
Tuya controllers (such as the [ERS-10TZBVK-AA](https://www.zigbee2mqtt.io/devices/ERS-10TZBVK-AA.html)) support binding but in a roundabout way: they will broadcast brightness up/brightness down/toggle commands on the first Group they're added to. So if you want to control a single bulb with the controller directly, you create a group containing only the knob and the bulb. Unfortunately, this means the net ends up with "isolation" groups to support these bindings, that shouldn't necessarily be exposed to Bifrost. I propose we add a boolean to the rooms config like so:

```
rooms:
  desk_light_isolation:
    name: Desk Light Isolation Group
    hidden: true
```

which will prevent the group from being exported into BiFrost. Thanks!
