### ISSUE TITLE
HAOS Addon error - Failed to parse critical z2m bridge message on [bridge/devices]

### ISSUE THREAD

**Issue by tbgoose** [chrivers/bifrost#26]
I have now successfully installed the hassio-addon on my HAOS x86 system.

@chrivers Looks like you are indeed correct. Even though I seem to be running the latest version of z2m, my commit is 'unknown' in z2m details page. Not sure what to do about that, or if it is a red herring.

Home Assistant
```
Core 2024.8.3
Supervisor 2024.08.0
Operating System 13.1
```

Z2M
```
Zigbee2MQTT version 1.40.0 commit: unknown
Coordinator type zStack3x0
Coordinator revision 20230507
Coordinator IEEE Address 0x00124b0024c166dc
```

config.yaml
```
bridge:
  name: Bifrost
  mac: XX:XX:XX:XX:XX
  ipaddress: 192.168.X.XXX
  netmask: 255.255.255.0
  gateway: 192.168.X.X
  timezone: XXXX/XXXX

z2m:
  server1:
    url: ws://192.168.X.XXX:8099`
```

Bifrost Addon Logs
` 
see below
`
