### ISSUE TITLE
Store config.yaml and state.yaml In A Separate Directory By Default

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [chrivers/bifrost#80]
Storing the `config.yaml` and `state.yaml` in separate directories would be extremely beneficial especially when using the Docker container route as this would allow for a persistable Docker volume to be used instead of a Bind mount. This can already be achieved in a Docker environment for the certs file. See [Docker Compose Volumes section here](https://github.com/chrivers/bifrost/issues/79#issuecomment-2645351108_) for how volumes can be used over bind mounts

It would also allow for future improvements to be made further up the chain such as in the Docker build file, the example `config.yaml` file could be automatically cloned to the directory with all of its correct permissions.

**Comment by chrivers** [comment]
Just to point out, this is already possible, it just requires a bit of manual configuration.

Quoting the [config reference](https://github.com/chrivers/bifrost/blob/master/doc/config-reference.md):

```yaml
# Bifrost section [optional!]
#
# Contains bifrost server settings
# [usually omitted, to use defaults]
bifrost:
  # name of yaml file to write state database to
  state_file: "state.yaml"

  # name of x509 certificate for https
  #
  # if this file is missing, bifrost will generate one for you
  #
  # if this file exists, bifrost will check that the mac address
  # matches the specified server mac address
  #
  # to generate a fresh certificate, rename/move this file
  # (this might require pairing the Hue App again)
  cert_file: "cert.pem"
```

You could set these values to e.g. `data/state.yaml` and `data/cert.pem`, and then mount the `data` dir into the container.

I agree that the docker template, and the corresponding instructions, could probably be a little clearer on this.
