### ISSUE TITLE
Bifrost runs, but not able to be configured in Hue app (HA add-on)

### ISSUE THREAD

**Issue by Intecpsp** [chrivers/bifrost#88]
This issue is being opened up following chatter from [Discord](https://discord.com/channels/1276604041727578144/1276604042511909048/1344046559880286230).

The first part was not being able to get Bifrost connected to Z2M (also HA add-on) or set up it's own bridge. I think the documentation around the config set up can be expanded here to fix that. Below are my configs

Z2M `configuration.yaml` snippet
```
frontend:
  enabled: true
  port: 8099 # The recommended HA port
  auth_token: <REDACTED>
```
Bifrost `config.yaml` snippets
```
bridge:
  name: Bifrost
  mac: <REDACTED> # MAC address of the HA server, can be found in internet router
  ipaddress: 192.168.10.234 # IP address of the HA server, can be found in Settings > System > Network > IPv4
  netmask: 255.255.255.0 # Network Mask of the HA server, can be found in Settings > System > Network > IPv4
  gateway: 192.168.10.1 # Gateway of the HA server, can be found in Settings > System > Network > IPv4
  timezone: Europe/Copenhagen # Hardcoded for now, only record found in https://github.com/chrivers/bifrost/blob/8957fa4ce32a1d463de8ccd5b356b62b2f2c3e51/src/hue/legacy_api.rs#L794
...
z2m:
  some-server:
    url: ws://homeassistant.local:8099/api?token=<REDACTED>
```
Also, in the Z2M config in the HA UI (Settings > Add-ons > Zigbee2MQTT > Configuration), go to the `Network` section at the bottom and move the `Show disabled ports` slider, then enter `8099` in the `Frontend tcp-listen port`, then `Save`, and `Restart` when prompted.

After getting that sorted out (and confirming NOTHING else on the HA server is using ports 80 or 443; oh, and deleting the generated `cert.pem` file for fresh generation) I came across [this](https://github.com/user-attachments/assets/0607bef6-a425-4678-b464-6e4c7a34e00b) flow preventing me from adding the bridge to my app. Turns out, it's the Hue account causing issues. So I had to sign out (also, clear all storage from device), and then set up the app again WITHOUT a Hue account.

Now we're stuck on the current issue. The app hangs when trying to set up the timezone: [video](https://github.com/user-attachments/assets/4c6b4f48-629f-4358-8efb-0470a7ae46b3). I can confirm the Bifrost server and Ha server times appear to be in sync.

Update: just tried the dev branch, same behavior.
